### ISSUE TITLE
nanogrep on NetBSD

### ISSUE THREAD

**Issue by voidpin** [Uniminin/nanogrep#1]
FYI, I've packaged `nanogrep` for NetBSD.
The package is currently in the WIP-repo due to:
-ongoing pkgsrc freeze ahead of the Q4-release, no new package should be imported.
-lack of a github release-tag, this is needed as we (on NetBSD) don't pull packages from crates.io

https://mail-index.netbsd.org/pkgsrc-wip-changes/2020/12/24/msg018928.html

If, you could also provide a github-tag whenever you make a new release in crates.io, I'll be happy to import `nanogrep` into the main branch and maintain the package once the freeze is over.

**Comment by Uniminin** [comment]
@voidpin Done! :)

**Comment by voidpin** [comment]
Awesome, thx! I'll update the package in WIP and merge it into main as soon as the freeze is over, a week or so.

**Comment by voidpin** [comment]
@Uniminin
Updated, https://mail-index.netbsd.org/pkgsrc-wip-changes/2020/12/26/msg018947.html

**Comment by voidpin** [comment]
@Uniminin `nanogrep` updated and merged into the main branch ;)

**Comment by Uniminin** [comment]
Fantastic! Amazing job!
